name: CI
 
on: push
env:
  CI: true
 
jobs:
    lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18.x, 20.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with: 
            node-vers: ${{ matrix.node-version }}
            cache: 'npm'
            run: make lint
    jest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Testing
          run: make test
    coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: CodeClimate Test Coverage
          uses: paambaati/codeclimate-action@v5.0.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          with:
            coverageCommand: make test-cov    